server:
  port: 80
  hostname: http://localhost:80
#  ssl:
#    enabled: true
#    key-alias: local_ssl
#    key-store: classpath:local-ssl.p12
#    key-store-type: PKCS12
#    key-password: 1234567
#    key-store-password: 1234567

spring:
  # (Data Source)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SpringForumApp_DB
    username: postgres
    password: 12345
  # Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  #HTTP  PUT, PATCH, DELETE
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #mail
  mail:
    host: smtp.yandex.ru
    username: springforumapp@yandex.ru
    password: c9n2kqlzn1h8q
    port: 465
    protocol: smtps

mail:
  debug: true

jwt:
  secret: wqeqwzcdasdasdcazcdas
